# .streamlit/config.toml
[theme]
primaryColor = "#4CAF50" # Green accent
backgroundColor = "#F0F2F6" # Light background
secondaryBackgroundColor = "#FFFFFF" # White for sidebar
textColor = "#333333" # Dark gray text
font = "sans serif" # Can be "sans serif", "serif", or "monospace"